name: tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: Install testing dependencies
      run: yarn install

    - name: Run Tests
      run: yarn test
